appointments/urls.py
from django.urls import path
from . import views
from .views import buscar_medicos

app_name = 'appointments'

urlpatterns = [
    path('buscar/', views.buscar_medicos, name='buscar_medicos'),
    # Puedes agregar otras rutas relacionadas a turnos o citas aquí
    path('medico/<int:medico_id>/horarios/', views.obtener_horarios_medico, name='obtener_horarios_medico'),
    path('crear_turno/', views.crear_turno, name='crear_turno'),
    path('confirmacion/', views.confirmacion_turno, name='confirmacion_turno'),
    ]

clinic_admin/urls.py
from django.urls import path
from . import views

app_name = 'clinic_admin'

urlpatterns = [
    path('home/', views.home_admin, name='home_admin'),
    path('edit_profile_admin/', views.edit_profile_admin, name='edit_profile_admin'),
    path('home/ficha_pacientes/', views.ficha_pacientes, name='ficha_pacientes'),
    path('home/turnos_pacientes/<int:paciente_id>/', views.turnos_paciente_ajax, name='turnos_paciente_ajax'),
    path('home/cancelar_turno/<int:turno_id>/', views.cancelar_turno, name='cancelar_turno'),
    path('agenda_medicos/', views.medicos_y_turnos_view, name='agenda_medicos'),
    path("medico/<int:medico_id>/editar_horarios/", views.editar_horarios_medico, name="editar_horarios_medico"),
    path("medico/<int:medico_id>/guardar_horarios/", views.guardar_horarios_medico, name="guardar_horarios_medico"),
    path("gestionar_medicos/", views.gestionar_medicos, name="gestionar_medicos"),
]

medi_turno/urls.py
# mediturno/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('appointments/', include('appointments.urls')),
    path('notificaciones/', include('notifications.urls', namespace='notifications')),
    path('', lambda request: redirect('users:home')),
    path('clinic_admin/', include('clinic_admin.urls')),
]

notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path('', views.notificaciones_turnos, name='lista_notificaciones'),
]

users/urls.py
from django.urls import path
from .views import login_view, register_view, home_view, map_view, edit_profile, logout_view, suggest_turno_view, soporte_view
from appointments.views import buscar_medicos

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('home/', home_view, name='home'),
    path('map/<int:user_id>/', map_view, name='map'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('logout/', logout_view, name='logout'),
    path('home/appointments', buscar_medicos, name='buscar_medico'),
    path('suggest_turno/', suggest_turno_view, name='suggest_turno'),
    path('soporte/', soporte_view, name='soporte'),
]

templates/includes/header.html
<header class="main-header">
<div class="logo">
    {% load static %}
    <a href="{% url 'users:home' %}">
        <img src="{% static 'img/mediturno_logo.png' %}" alt="Mediturno" class="logo-img">
    </a>
</div>

    <button class="hamburger" onclick="toggleMenu()">☰</button>

    <nav id="mobileMenu" class="mobile-menu hidden">
        <button class="close-button" onclick="toggleMenu()">✕</button>
        <ul>
            <li><a href="{% url 'users:home' %}">Inicio</a></li>
            <li><a href="{% url 'notifications:lista_notificaciones' %}">Recordatorios</a></li>
            <li><a href="{% url 'appointments:buscar_medicos' %}">Turnos</a></li>
            <li><a href="{% url 'users:suggest_turno' %}">Calendario</a></li>
            <li><a href="{% url 'users:soporte' %}">Soporte</a></li>
            <li><a href="{% url 'users:edit_profile' %}">Configuración</a></li>
            <li><a href="#" id="toggle-dark-mode" onclick="toggleDarkMode(); return false;">Modo oscuro</a></li>
            <li><a href="{% url 'users:logout' %}">Cerrar sesión</a></li>
        </ul>
    </nav>
</header>

templates/includes/header_admin.html
<header class="main-header">
<div class="logo">
    {% load static %}
    <a href="{% url 'clinic_admin:home_admin' %}">
        <img src="{% static 'img/mediturno_logo.png' %}" alt="Mediturno" class="logo-img">
    </a>
</div>

    <button class="hamburger" onclick="toggleMenu()">☰</button>

    <nav id="mobileMenu" class="mobile-menu hidden">
        <button class="close-button" onclick="toggleMenu()">✕</button>
        <ul>
            <li><a href="{% url 'clinic_admin:home_admin' %}">Inicio</a></li>
            <li><a href="{% url 'clinic_admin:gestionar_medicos' %}">Medicos</a></li>
            <li><a href="{% url 'clinic_admin:ficha_pacientes' %}">Pacientes</a></li>
            <li><a href="{% url 'clinic_admin:agenda_medicos' %}">Agenda</a></li>
            <li><a href="{% url 'users:soporte' %}">Soporte</a></li>
            <li><a href="{% url 'clinic_admin:edit_profile_admin' %}">Configuración</a></li>
            <li><a href="#" id="toggle-dark-mode" onclick="toggleDarkMode(); return false;">Modo oscuro</a></li>
            <li><a href="{% url 'users:logout' %}">Cerrar sesión</a></li>
        </ul>
    </nav>
</header>