appointments/urls.py
from django.urls import path
from . import views
from .views import buscar_medicos

app_name = 'appointments'

urlpatterns = [
    path('buscar/', views.buscar_medicos, name='buscar_medicos'),
    # Puedes agregar otras rutas relacionadas a turnos o citas aquí
    path('medico/<int:medico_id>/horarios/', views.obtener_horarios_medico, name='obtener_horarios_medico'),
    path('crear_turno/', views.crear_turno, name='crear_turno'),
    path('confirmacion/', views.confirmacion_turno, name='confirmacion_turno'),
    ]

medi_turno/urls.py
# mediturno/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('appointments/', include('appointments.urls')),
    path('notificaciones/', include('notifications.urls', namespace='notifications')),
    path('', lambda request: redirect('users:home')),
    path('clinic_admin/', include('clinic_admin.urls')),
]

notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path('', views.notificaciones_turnos, name='lista_notificaciones'),
]

users/urls.py
from django.urls import path
from .views import login_view, register_view, home_view, map_view, edit_profile, logout_view, suggest_turno_view, soporte_view
from appointments.views import buscar_medicos

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('home/', home_view, name='home'),
    path('map/<int:user_id>/', map_view, name='map'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('logout/', logout_view, name='logout'),
    path('home/appointments', buscar_medicos, name='buscar_medico'),
    path('suggest_turno/', suggest_turno_view, name='suggest_turno'),
    path('soporte/', soporte_view, name='soporte'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import RegexValidator, ValidationError
from django.utils.timezone import now
from django.contrib.auth.models import BaseUserManager

#dias
class DiaDeAtencion(models.Model):
    DIA_CHOICES = [
        ('LU', 'Lunes'),
        ('MA', 'Martes'),
        ('MI', 'Miércoles'),
        ('JU', 'Jueves'),
        ('VI', 'Viernes'),
        ('SA', 'Sábado'),
        ('DO', 'Domingo'),
    ]
    codigo = models.CharField(max_length=2, choices=DIA_CHOICES, unique=True)

    def __str__(self):
        return dict(self.DIA_CHOICES)[self.codigo]


def validate_birth_date(value):
    if value > now().date():
        raise ValidationError("La fecha de nacimiento no puede estar en el futuro.")

#Esta clase es para poder crear el super admin si necesidad de agregar todos los campos
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, password, **extra_fields)

#Aca esta el usuario base
class CustomUser(AbstractUser):
    objects = CustomUserManager()
    
    USER_TYPES = (
        ('user', 'User'),
        ('medic', 'Medic'),
        ('clinic', 'Clinic'),
    )
    OBRA_SOCIAL_CHOICES = (
        ('osde', 'OSDE'),
        ('swiss_medical', 'Swiss Medical'),
        ('galeno', 'Galeno'),
        ('medife', 'Medifé'),
        ('other', 'Other')
    )
    CIUDAD_CHOICES = (
        ('villa_gesell', 'Villa Gesell'),
        ('pinamar', 'Pinamar'),
        ('madariaga', 'Madariaga'),
    )

    role = models.CharField(max_length=10, choices=USER_TYPES, default='user', blank=True, null=True)

    obra_social = models.CharField(
        max_length=20,
        choices=OBRA_SOCIAL_CHOICES,
        default='other',
        blank=True,
        null=True
    )

    numero_afiliado = models.CharField(
        max_length=20,
        unique=True,
        null=True,
        blank=True,
        validators=[
            RegexValidator(
                regex=r'^\d{8,12}$',
                message="Número de afiliado debe contener entre 8 y 12 dígitos numéricos",
                code='invalid_numero_afiliado'
            )
        ]
    )

    dni = models.CharField(
        max_length=8,
        null=True,
        blank=True,
        validators=[
            RegexValidator(
                regex=r'^\d{8}$',
                message="El DNI debe contener exactamente 8 dígitos numéricos",
                code='invalid_dni'
            )
        ]
    )

    email = models.EmailField(unique=True)
    nombre = models.CharField(max_length=50,blank=True,null=True)
    apellido = models.CharField(max_length=50, blank=True, null=True)
    fecha_nacimiento = models.DateField(validators=[validate_birth_date], blank=True, null=True)

    telefono = models.CharField(
        max_length=15,
        blank=True,
        null=True,
        validators=[
            RegexValidator(
                regex=r'^\+?\d{7,15}$',
                message="El teléfono debe contener entre 7 y 15 dígitos, opcionalmente con un prefijo internacional.",
                code='invalid_telefono'
            )
        ]
    )

    ciudad = models.CharField(
        max_length=50,
        choices=CIUDAD_CHOICES,
        default='villa_gesell',
        blank=True,
        null=True
    )

    direccion = models.CharField(
        max_length=2048,
        blank=True,
        null=True
    )

    def is_medic(self):
        return self.role == 'medic'

    def is_clinic(self):
        return self.role == 'clinic'

    def is_admin(self):
        return self.is_superuser
    
class Especialidad(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre

class MedicoProfile(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, related_name='medico_profile')
    especialidades = models.ManyToManyField('Especialidad', related_name='medicos')
    clinica = models.ForeignKey(
        'CustomUser',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        limit_choices_to={'role': 'clinic'},
        related_name='medicos_en_clinica'
    )
    matricula = models.CharField(max_length=30)

    def __str__(self):
        return f"Dr. {self.user.nombre} {self.user.apellido} - {', '.join([e.nombre for e in self.especialidades.all()])}"
"""
    def clean(self):
        # Si ya existe, validamos que tenga al menos un horario
        if self.pk and not self.horarios.exists():
            raise ValidationError("El medico debe tener al menos un horario cargado.")
"""
class ClinicaProfile(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, related_name='clinica_profile')
    nombre_comercial = models.CharField(max_length=100)
    razon_social = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return self.nombre_comercial
"""
    def clean(self):
        # Si ya existe, validamos que tenga al menos un horario
        if self.pk and not self.horarios.exists():
            raise ValidationError("La clínica debe tener al menos un horario cargado.")
"""
#Es para hacer los horarios de las clinicas y que puedan ser asimetricos ej: de LU a VI un horario y los SA otro:

class HorarioClinica(models.Model):
    clinica = models.ForeignKey('ClinicaProfile', on_delete=models.CASCADE, related_name='horarios')
    dia = models.CharField(max_length=2, choices=DiaDeAtencion.DIA_CHOICES)
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()

    class Meta:
        unique_together = ('clinica', 'dia')

    def __str__(self):
        return f"{self.get_dia_display()}: {self.hora_inicio} - {self.hora_fin}"

class HorarioMedico(models.Model):
    medico = models.ForeignKey('MedicoProfile', on_delete=models.CASCADE, related_name='horarios')
    dia = models.CharField(max_length=2, choices=DiaDeAtencion.DIA_CHOICES)
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()

    class Meta:
        unique_together = ('medico', 'dia')

    def __str__(self):
        return f"{self.get_dia_display()}: {self.hora_inicio} - {self.hora_fin}"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.utils.translation import gettext_lazy as _

class LoginForm(forms.Form):
    username = forms.CharField(label="Usuario")
    password = forms.CharField(widget=forms.PasswordInput, label="Contraseña")


class CustomUserCreationForm(UserCreationForm):
    fecha_nacimiento = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        label="Fecha de Nacimiento"# Usa el selector nativo del navegador
    )
    class Meta:
        model = CustomUser
        fields = ['username', 'nombre', 'apellido', 'dni', 'fecha_nacimiento', 'email', 'password1', 'password2']
        labels = {
            'username': 'Usuario',
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'dni': 'DNI',
            'fecha_nacimiento': 'Fecha de Nacimiento',
            'email': 'Email',
            'password1': 'Contraseña',
            'password2': 'Confirmar Contraseña'
        }
        # No incluimos 'role'
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        # Sobreescribir los labels de password1 y password2
        self.fields['password1'].label = 'Contraseña'
        self.fields['password2'].label = 'Confirmar Contraseña'
    def save(self, commit=True):
        user = super().save(commit=False)
    
    # Asignar automáticamente rol 'user' si no se definió
        if not user.role:
            user.role = 'user'

    # Si es una clínica, limpiar nombre y apellido
        if user.role == 'clinic':
            user.nombre = ''
            user.apellido = ''

        if commit:
            user.save()
        return user

class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            'nombre', 'apellido', 'email', 'dni', 'fecha_nacimiento', 'telefono',
            'obra_social', 'numero_afiliado', 'ciudad'
        ]
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
        }

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import LoginForm, CustomUserCreationForm, CustomUserUpdateForm
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm 
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .models import CustomUser
from appointments.models import Appointment
from datetime import timedelta, datetime, time
from users.models import HorarioMedico, DiaDeAtencion
import calendar

def login_view(request):
    form = LoginForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        user = authenticate(
            request,
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        if user is not None:
            login(request, user)  # 👈 Esto es lo que faltaba
            if user.role in ['clinic', 'medic']:
                return redirect('clinic_admin:home_admin')
            else:
                return redirect('users:home')
        else:
            form.add_error(None, "Nombre de usuario o contraseña incorrectos")


    return render(request, 'users/login.html', {'form': form})


def register_view(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  # Se guarda con rol 'user'
            login(request, user)  # Iniciar sesión después del registro
            return redirect("users:login")  # Redirigir a la página principal
    else:
        form = CustomUserCreationForm()

    return render(request, "users/register.html", {"form": form})


# en users/views.py


def logout_view(request):
    logout(request)
    return redirect('users:login')

@login_required(login_url='/users/login/')
def home_view(request):
    return render(request, 'users/home.html')

@login_required(login_url='/users/login/')
def map_view(request, user_id):
    user = get_object_or_404(CustomUser, pk=user_id)
    return render(request, 'users/map.html', {'direccion': user.direccion})

@login_required(login_url='/users/login/')
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect("users:home")
    else:
        form = CustomUserUpdateForm(instance=user)
    return render(request, 'users/edit_profile.html', {'form': form})


def get_next_available_date(medic, suggested_date):
    horarios = HorarioMedico.objects.filter(medico=medic.medico_profile)
    dias_laborales = set(h.dia for h in horarios)
    dia_map = {k: i for i, (k, _) in enumerate(DiaDeAtencion.DIA_CHOICES)}
    dias_laborales_weekdays = set(dia_map[d] for d in dias_laborales if d in dia_map)
    current_date = suggested_date.date() if suggested_date else datetime.now().date()
    for _ in range(60):
        weekday = current_date.weekday()
        if weekday in dias_laborales_weekdays:
            for horario in horarios.filter(dia=[k for k, v in dia_map.items() if v == weekday][0]):
                start_time = horario.hora_inicio
                end_time = horario.hora_fin
                slot_time = datetime.combine(current_date, start_time)
                while slot_time.time() < end_time:
                    exists = Appointment.objects.filter(
                        medico=medic,
                        fecha_inicio=slot_time,
                    ).exists()
                    if not exists:
                        return slot_time
                    slot_time += timedelta(hours=1)
        current_date += timedelta(days=1)
    return None

@login_required(login_url='/users/login/')
def suggest_turno_view(request):
    user = request.user
    medic_ids = Appointment.objects.filter(paciente=user).values_list('medico_id', flat=True)
    unique_medic_ids = set(medic_ids)
    suggestions = []

    for medic_id in unique_medic_ids:
        medic = CustomUser.objects.get(id=medic_id)
        turns = Appointment.objects.filter(paciente=user, medico_id=medic_id).order_by('-fecha_inicio')[:3]
        turns = list(turns)
        suggested_date = None

        if len(turns) >= 2:
            intervals = [
                (turns[i].fecha_inicio - turns[i+1].fecha_inicio).days
                for i in range(len(turns)-1)
            ]
            avg_interval = sum(intervals) // len(intervals)
            initial_suggested = turns[0].fecha_inicio + timedelta(days=avg_interval)
            suggested_date = get_next_available_date(medic, initial_suggested)

        suggestions.append({
            'medic': medic,
            'turns': turns,
            'suggested_date': suggested_date,
        })

    return render(request, 'users/suggest_turno.html', {
        'suggestions': suggestions,
    })


@login_required(login_url='/users/login/')
def soporte_view(request):
    if request.user.role in ['clinic', 'medic']:
        return render(request, 'soporte_admin.html')
    return render(request, 'soporte.html')

users/templates/users/base_auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>{% block title %}MediTurno{% endblock %}</title>
    <script src="https://unpkg.com/htmx.org@1.9.2"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/auth.css' %}">


</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

users/templates/users/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Mediturno - Editar Perfil</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/map.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

    <script src="{% static 'js/menu.js' %}" defer></script>
    <script src="{% static 'js/darkmode.js' %}"></script>
</head>
<body>
    {% include "includes/header.html" %}
    <h2>Editar Perfil</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Cambios</button>
    </form>

</body>
</html>

users/templates/users/home.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Mediturno - Inicio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/home.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

    <script src="{% static 'js/menu.js' %}" defer></script>
    <script src="{% static 'js/darkmode.js' %}"></script>
</head>

<body>
    {% include "includes/header.html" %}
    <main class="home-buttons">
        <button onclick="location.href='{% url 'notifications:lista_notificaciones' %}'">Recordatorio rápido</button>
        <button onclick="location.href='{% url 'appointments:buscar_medicos' %}'">Pedidos de turno</button>
        <button onclick="location.href='{% url 'users:suggest_turno' %}'">Calendario</button>
    </main>
</body>

</html>

users/templates/users/login.html
{%extends "users/base_auth.html" %}

{% block content %}
<h2>Iniciar Sesion</h2>
   <form class="form-with-validation" action="{% url 'users:login' %}" method="post" class="auth-form">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            <span class="error-message">
                {{ field.errors }}
            </span>
        </div>
    {% endfor %}
    
    {% if form.non_field_errors %}
        <div class="form-errors">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <div class="btn-group">
        <button class="form-submit">Iniciar Sesion</button>
        <a href="{% url 'users:register' %}" class="secondary-btn">Registrarse</a>
    </div>
</form> <!-- initial load will auto-fetch partial -->

{% endblock %}

users/templates/users/map.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Mediturno - Mapa</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/map.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

    <script src="{% static 'js/menu.js' %}" defer></script>
    <script src="{% static 'js/darkmode.js' %}"></script>
</head>
<body>
    {% include "includes/header.html" %}
    <div class="map_wrapper">
        <iframe width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"
            src="{{ direccion }}">
        </iframe>
    </div>

</body>
</html>

users/templates/users/register.html
{% extends "users/base_auth.html" %}

{% block title %}
    Registrarse
{% endblock %}

{% block content %}
    <h1>Registrarse</h1>
    <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Improves layout with paragraph tags -->
        <button class="form-submit">Registrarse</button>
    </form>
{% endblock %}

users/templates/users/suggest_turno.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Mediturno - Sugerir Turno</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'users/css/suggest_turno.css' %}">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

    <script src="{% static 'js/menu.js' %}" defer></script>
    <script src="{% static 'js/darkmode.js' %}"></script>
</head>

<body>
    {% include "includes/header.html" %}
    
    <div class="contenido-sugerencias">
        <h2>Sugerencias de próximos turnos</h2>

        {% for item in suggestions %}
        <div class="medic-suggestion">
            <h3>{{ item.medic.nombre }} {{ item.medic.apellido }}</h3>   

            {% if item.suggested_date %}
            <p class="sugerencia">
                <a href="{% url 'appointments:buscar_medicos' %}">
                    Sugerencia: <strong>{{ item.suggested_date|date:"d/m/Y" }}</strong>
                </a>
            </p>
            {% else %}
            <p class="sugerencia vacia">No hay suficientes turnos previos para sugerir una fecha.</p>
            {% endif %}
        </div>
        {% empty %}
        <p class="sugerencia vacia">No hay turnos previos.</p>
        {% endfor %}
    </div>
</body>


</html>